const Tag = require('./model')
const repository = require('./repository')
const { getSystemTime } = require('../core/time')

const _ = {}

// Resolves the deleted_at value to store on update. The client sends a boolean, never a
//  timestamp: true stamps the current system time, false clears the mark, and null (or an
//  absent field) does nothing — it keeps whatever the stored row already had.
_.resolveDeletedAt = (current, deleted_at_flag) => {
    if (deleted_at_flag === undefined || deleted_at_flag === null) return current ? current.deleted_at : null
    return deleted_at_flag ? getSystemTime() : null
}

// Builds a Tag from a create request. The id is generated by the model and deleted_at
//  defaults to null; metadata keeps the model default ('{}') when the client omits it.
_.buildForCreate = (body) => {
    const tag = new Tag()
    tag.name = body.name
    if (body.metadata !== undefined) tag.metadata = body.metadata
    return tag
}

// Builds a Tag from an update request. It resolves deleted_at itself from the stored row
//  and the client flag, so the controller does not deal with timestamps.
_.buildForUpdate = (current, body) => {
    const deleted_at = _.resolveDeletedAt(current, body.deleted_at)
    const tag = new Tag()
    tag.setClass(body.id, body.name, body.metadata, deleted_at)
    return tag
}

// Tag names are unique and case-insensitive. Soft-deleted tags still hold their name, so
//  they count as taken here.
_.isNameTaken = (name) => repository.getByName(name) !== null

// Same rule, but ignoring the tag being updated so it can keep its own name.
_.isNameTakenByAnother = (name, id) => {
    const clash = repository.getByName(name)
    if (!clash) return false
    return clash.id !== id
}

// Soft-delete: stamp deleted_at instead of removing the row, so existing relations and
//  search history keep pointing to a valid tag.
_.softDelete = (id) => repository.softDelete(id, getSystemTime())

module.exports = _
