const WorkSpace = require('./model')
const repository = require('./repository')
const { getSystemTime } = require('../core/time')

const _ = {}

// --------------------------------------------------------------------------------
// Data access. This service is the only door to repository.js: a controller never
//  reaches the repository itself, it always comes through here.
// --------------------------------------------------------------------------------
_.getAll = () => repository.getAll()
_.getById = (id) => repository.getById(id)
_.create = (workspace) => repository.post(workspace)
_.update = (workspace) => repository.update(workspace)

// Resolves the deleted_at value to store on update. The client sends a boolean, never a
//  timestamp: true stamps the current system time, false clears the mark, and null (or an
//  absent field) does nothing — it keeps whatever the stored row already had.
_.resolveDeletedAt = (current, deleted_at_flag) => {
    if (deleted_at_flag === undefined || deleted_at_flag === null) return current ? current.deleted_at : null
    return deleted_at_flag ? getSystemTime() : null
}

// Builds a WorkSpace from a create request. The id is generated by the database and
//  deleted_at defaults to null.
_.buildForCreate = (body) => {
    const workspace = new WorkSpace()
    workspace.name = body.name
    workspace.path_absolute = body.path_absolute
    workspace.path_relative = body.path_relative
    return workspace
}

// Builds a WorkSpace from an update request. It resolves deleted_at itself from the stored row
//  and the client flag, so the controller does not deal with timestamps.
_.buildForUpdate = (current, body) => {
    const deleted_at = _.resolveDeletedAt(current, body.deleted_at)
    const workspace = new WorkSpace()
    workspace.setClass(body.id, body.name, body.path_absolute, body.path_relative, deleted_at)
    return workspace
}

// The absolute path is what actually identifies a workspace on the filesystem, so it is the
//  UNIQUE column. Soft-deleted workspaces still hold their path, so they count as taken here.
_.isPathTaken = (path_absolute) => repository.getByPathAbsolute(path_absolute) !== null

// Same rule, but ignoring the workspace being updated so it can keep its own path.
_.isPathTakenByAnother = (path_absolute, id) => {
    const clash = repository.getByPathAbsolute(path_absolute)
    if (!clash) return false
    return clash.id !== id
}

// Soft-delete: stamp deleted_at instead of removing the row, so existing relations keep
//  pointing to a valid workspace.
_.softDelete = (id) => repository.softDelete(id, getSystemTime())

// Hard-delete: physically removes the row. Deliberately not wired to any HTTP endpoint —
//  it exists for backend code that genuinely needs to purge a record.
_.hardDelete = (id) => repository.deleteById(id)

module.exports = _
