const _ = {}

_.isString = v => typeof v === 'string'
_.isNumber = v => typeof v === 'number'
_.isBoolean = v => typeof v === 'boolean'
_.isNumberOrNull = v => v === null || typeof v === 'number'
// Ids arriving in the URL are strings (`req.params.id`). The controller passes them through
//  Number() first, and this says whether the result is a usable id: the database assigns them as
//  INTEGER PRIMARY KEY, so they are whole and start at 1.
_.isId = v => Number.isInteger(v) && v > 0

// Validates the body of a create request. The id is generated by the database and deleted_at is
//  not accepted here, so only the data fields are checked.
_.validatePost = (body) => {
    if (!_.isString(body.name)) return false
    if (!_.isString(body.path_absolute)) return false
    if (!_.isString(body.path_relative)) return false
    return true
}

// Validates the body of an update request. deleted_at is the client flag: a boolean, or
//  null/absent to leave the stored value untouched.
_.validateUpdate = (body) => {
    if (!_.isNumber(body.id)) return false
    if (!_.isString(body.name)) return false
    if (!_.isString(body.path_absolute)) return false
    if (!_.isString(body.path_relative)) return false
    if (body.deleted_at !== undefined && body.deleted_at !== null && !_.isBoolean(body.deleted_at)) return false
    return true
}

module.exports = _
