const Metadata = require('./model')
const repository = require('./repository')
const { getSystemTime } = require('../core/time')

const _ = {}

// --------------------------------------------------------------------------------
// Data access. This service is the only door to repository.js: a controller never
//  reaches the repository itself, it always comes through here.
// --------------------------------------------------------------------------------
_.getAll = () => repository.getAll()
_.getById = (id) => repository.getById(id)
_.getByName = (name) => repository.getByName(name)
_.create = (metadata) => repository.post(metadata)
_.update = (metadata) => repository.update(metadata)

// Resolves the deleted_at value to store on update. The client sends a boolean, never a
//  timestamp: true stamps the current system time, false clears the mark, and null (or an
//  absent field) does nothing — it keeps whatever the stored row already had.
_.resolveDeletedAt = (current, deleted_at_flag) => {
    if (deleted_at_flag === undefined || deleted_at_flag === null) return current ? current.deleted_at : null
    return deleted_at_flag ? getSystemTime() : null
}

// Builds a Metadata from a create request. The id is generated by the model and deleted_at
//  defaults to null; the client provides only the data fields.
_.buildForCreate = (body) => {
    const metadata = new Metadata()
    metadata.name = body.name
    metadata.value = body.value
    return metadata
}

// Builds a Metadata from an update request. It resolves deleted_at itself from the stored
//  row and the client flag, so the controller does not deal with timestamps.
_.buildForUpdate = (current, body) => {
    const deleted_at = _.resolveDeletedAt(current, body.deleted_at)
    const metadata = new Metadata()
    metadata.setClass(body.id, body.name, body.value, deleted_at)
    return metadata
}

// Metadata names are unique (case-sensitive, the column has no COLLATE NOCASE). Soft-deleted
//  records still hold their name, so they count as taken here: re-creating a name that sits in
//  the trash can is a 409, not a UNIQUE constraint blowing up as a 500.
_.isNameTaken = (name) => repository.getByName(name) !== null

// Same rule, but ignoring the record being updated so it can keep its own name.
_.isNameTakenByAnother = (name, id) => {
    const clash = repository.getByName(name)
    if (!clash) return false
    return clash.id !== id
}

// Soft-delete: stamp deleted_at instead of removing the row, so the record stays readable
//  and the client can show it in a trash can. This is what the DELETE endpoint calls.
_.softDeleteByName = (name) => repository.softDeleteByName(name, getSystemTime())

// Hard-delete: physically removes the row. Deliberately not wired to any HTTP endpoint —
//  it exists for backend code that genuinely needs to purge a record.
_.hardDeleteByName = (name) => repository.deleteByName(name)

module.exports = _
