const _ = {}

_.isString = v => typeof v === 'string'
_.isNumber = v => typeof v === 'number'
_.isBoolean = v => typeof v === 'boolean'
_.isNumberOrNull = v => v === null || typeof v === 'number'

// Validates the body of a create request. The id is generated by the model and deleted_at is
//  not accepted here, so only the data fields are checked.
_.validatePost = (body) => {
    if (!_.isString(body.name)) return false
    if (!_.isString(body.value)) return false
    return true
}

// Validates the body of an update request. deleted_at is the client flag: a boolean, or
//  null/absent to leave the stored value untouched.
_.validateUpdate = (body) => {
    if (!_.isString(body.id)) return false
    if (!_.isString(body.name)) return false
    if (!_.isString(body.value)) return false
    if (body.deleted_at !== undefined && body.deleted_at !== null && !_.isBoolean(body.deleted_at)) return false
    return true
}

module.exports = _
