const { PORT } = require('../core/env')
const URL = `http://localhost:${PORT}`

const axios = require('axios')

const { SYSTEM_ENTITIES } = require('../core/constants')
const { RELATION_TYPES } = require('./types-of-relation')
const relation_repository = require('./repository')

const SAMPLE = {
    id_1: 100,
    entity_1: 'file',
    id_2: 200,
    entity_2: 'metadata',
    relation_type: 'linked',
    note: 'File 100 linked to metadata 200'
}

const SECOND_SAMPLE = {
    id_1: 100,
    entity_1: 'directory',
    id_2: 300,
    entity_2: 'directory',
    relation_type: 'contains',
    note: 'Directory 100 contains directory 300'
}

// The id is generated by the server, so we look created relations up by their note.
let sample_id = ''
let second_id = ''

async function findRelationIdByNote(note) {
    const res = await axios.get(`${URL}/api/relation/`, { validateStatus: () => true })
    const found = res.data.data.find(r => r.note === note)
    return found ? found.id : null
}

beforeAll(() => {
    relation_repository.deleteAll()
})

describe('GET /api/relation/entities/', () => {
    it('returns 200 with the enumerated list of system entities', async () => {
        const res = await axios.get(`${URL}/api/relation/entities/`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        expect(res.data.data).toEqual(SYSTEM_ENTITIES)
    })
})

describe('GET /api/relation/types/', () => {
    it('returns 200 with the fixed list of relation types', async () => {
        const res = await axios.get(`${URL}/api/relation/types/`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        expect(res.data.data).toEqual(RELATION_TYPES)
    })
})

describe('POST /api/relation/', () => {
    it('returns 400 warning on invalid body (id_1 not a number)', async () => {
        const res = await axios.post(`${URL}/api/relation/`, { ...SAMPLE, id_1: '100' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 400 warning on entity not in SYSTEM_ENTITIES', async () => {
        const res = await axios.post(`${URL}/api/relation/`, { ...SAMPLE, entity_1: 'not-a-real-entity' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 400 warning on relation_type not in RELATION_TYPES', async () => {
        const res = await axios.post(`${URL}/api/relation/`, { ...SAMPLE, relation_type: 'not-a-real-type' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 400 warning on missing relation_type', async () => {
        const no_type = { ...SAMPLE }
        delete no_type.relation_type
        const res = await axios.post(`${URL}/api/relation/`, no_type, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 201 on valid relation', async () => {
        const res = await axios.post(`${URL}/api/relation/`, SAMPLE, { validateStatus: () => true })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation created')

        sample_id = await findRelationIdByNote(SAMPLE.note)
        expect(typeof sample_id).toBe('number')
    })

    it('returns 201 on valid relation without note (note is nullable)', async () => {
        const no_note = { ...SECOND_SAMPLE }
        delete no_note.note
        const res = await axios.post(`${URL}/api/relation/`, no_note, { validateStatus: () => true })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')
    })

    it('allows a second relation for the same id_1 and a different id_2 (no uniqueness restriction)', async () => {
        const res = await axios.post(`${URL}/api/relation/`, SECOND_SAMPLE, { validateStatus: () => true })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation created')

        second_id = await findRelationIdByNote(SECOND_SAMPLE.note)
        expect(typeof second_id).toBe('number')
    })
})

describe('GET /api/relation/', () => {
    it('returns 200 with a data array', async () => {
        const res = await axios.get(`${URL}/api/relation/`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
    })
})

describe('GET /api/relation/id/:id', () => {
    it('returns 200 with the relation when found', async () => {
        const res = await axios.get(`${URL}/api/relation/id/${sample_id}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(res.data.data.id).toBe(sample_id)
        expect(res.data.data.entity_1).toBe(SAMPLE.entity_1)
        expect(res.data.data.entity_2).toBe(SAMPLE.entity_2)
        expect(res.data.data.relation_type).toBe(SAMPLE.relation_type)
    })

    it('returns 404 when the id does not exist', async () => {
        const res = await axios.get(`${URL}/api/relation/id/nonexistent-id`, { validateStatus: () => true })
        expect(res.status).toBe(404)
        expect(res.data.status).toBe('failed')
        expect(res.data.description).toBe('relation not found')
    })
})

describe('GET /api/relation/entity/:entity', () => {
    it('returns 200 with relations matching the entity', async () => {
        const res = await axios.get(`${URL}/api/relation/entity/${SAMPLE.entity_1}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        const ids = res.data.data.map(r => r.id)
        expect(ids).toContain(sample_id)
    })

    it('returns 400 warning when entity is not in SYSTEM_ENTITIES', async () => {
        const res = await axios.get(`${URL}/api/relation/entity/not-a-real-entity`, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation entity invalid')
    })
})

describe('GET /api/relation/entity_id/:id', () => {
    it('returns 200 with relations where the record id appears on either side', async () => {
        const res = await axios.get(`${URL}/api/relation/entity_id/${SAMPLE.id_1}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        const ids = res.data.data.map(r => r.id)
        expect(ids).toContain(sample_id)
        expect(ids).toContain(second_id)
    })

    it('returns 200 with empty array when no relation matches', async () => {
        const res = await axios.get(`${URL}/api/relation/entity_id/0`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        expect(res.data.data.length).toBe(0)
    })
})

describe('PUT /api/relation/update/', () => {
    it('returns 400 warning on invalid body (id_1 not a number)', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, { ...SAMPLE, id: sample_id, id_1: '100' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 404 when relation does not exist', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, { ...SAMPLE, id: 999999 }, { validateStatus: () => true })
        expect(res.status).toBe(404)
        expect(res.data.status).toBe('failed')
        expect(res.data.description).toBe('relation not found')
    })

    it('returns 200 on valid update (note and relation_type changed)', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, { ...SAMPLE, id: sample_id, relation_type: 'sibling', note: 'Updated note' }, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation updated')

        const get = await axios.get(`${URL}/api/relation/id/${sample_id}`, { validateStatus: () => true })
        expect(get.data.data.note).toBe('Updated note')
        expect(get.data.data.relation_type).toBe('sibling')
    })
})

describe('PUT /api/relation/update/ deleted_at', () => {
    const DELETED_SAMPLE = {
        id_1: 900,
        entity_1: 'file',
        id_2: 901,
        entity_2: 'tag',
        relation_type: 'tagged',
        note: 'trash-relation'
    }

    let target_id = ''

    // Builds the full update body the endpoint expects, adding the deleted_at field only
    //  when the test explicitly passes one.
    const buildBody = (deleted_at) => {
        const body = { ...DELETED_SAMPLE, id: target_id }
        if (deleted_at !== undefined) body.deleted_at = deleted_at
        return body
    }

    const readRelation = async () => {
        const res = await axios.get(`${URL}/api/relation/id/${target_id}`, { validateStatus: () => true })
        return res.data.data
    }

    beforeAll(async () => {
        await axios.post(`${URL}/api/relation/`, DELETED_SAMPLE, { validateStatus: () => true })
        target_id = await findRelationIdByNote(DELETED_SAMPLE.note)
    })

    it('stores null on a newly created relation', async () => {
        const relation = await readRelation()
        expect(relation.deleted_at).toBeNull()
    })

    it('stores the Unix Epoch in seconds when true is sent', async () => {
        const before = Math.floor(Date.now() / 1000)
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(true), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const relation = await readRelation()
        expect(typeof relation.deleted_at).toBe('number')
        expect(relation.deleted_at).toBeGreaterThanOrEqual(before)
        expect(relation.deleted_at).toBeLessThanOrEqual(Math.floor(Date.now() / 1000))
    })

    it('returns deleted relations in the full listing', async () => {
        const res = await axios.get(`${URL}/api/relation/`, { validateStatus: () => true })
        const relation = res.data.data.find(r => r.id === target_id)
        expect(relation).toBeDefined()
        expect(typeof relation.deleted_at).toBe('number')
    })

    it('returns a deleted relation when asked by id', async () => {
        const res = await axios.get(`${URL}/api/relation/id/${target_id}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(typeof res.data.data.deleted_at).toBe('number')
    })

    it('returns a deleted relation when querying by entity', async () => {
        const res = await axios.get(`${URL}/api/relation/entity/${DELETED_SAMPLE.entity_1}`, { validateStatus: () => true })
        const relation = res.data.data.find(r => r.id === target_id)
        expect(relation).toBeDefined()
        expect(typeof relation.deleted_at).toBe('number')
    })

    it('returns a deleted relation when querying by entity id', async () => {
        const res = await axios.get(`${URL}/api/relation/entity_id/${DELETED_SAMPLE.id_1}`, { validateStatus: () => true })
        const relation = res.data.data.find(r => r.id === target_id)
        expect(relation).toBeDefined()
        expect(typeof relation.deleted_at).toBe('number')
    })

    it('keeps the stored value when deleted_at is not sent', async () => {
        const before = await readRelation()
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(undefined), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const after = await readRelation()
        expect(after.deleted_at).toBe(before.deleted_at)
    })

    it('sets a newer Unix Epoch when true is sent on an already deleted relation', async () => {
        const before = await readRelation()
        expect(typeof before.deleted_at).toBe('number')

        // getSystemTime() works in whole seconds, so the clock must advance for the new
        //  value to be distinguishable from the previous one.
        await new Promise(resolve => setTimeout(resolve, 1100))

        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(true), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const after = await readRelation()
        expect(after.deleted_at).toBeGreaterThan(before.deleted_at)
    })

    it('clears the value back to null when false is sent', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(false), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const relation = await readRelation()
        expect(relation.deleted_at).toBeNull()
    })

    it('stays null when false is sent on a relation that was not deleted', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(false), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const relation = await readRelation()
        expect(relation.deleted_at).toBeNull()
    })

    it('returns 400 warning when deleted_at is not a boolean', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody('yes'), { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })
})

describe('DELETE /api/relation/id/:id', () => {
    it('returns 200 on delete', async () => {
        // Delete a throwaway relation so the sample relations persist in the database.
        await axios.post(`${URL}/api/relation/`, { ...SAMPLE, note: 'throwaway-relation' }, { validateStatus: () => true })
        const throwaway_id = await findRelationIdByNote('throwaway-relation')

        const res = await axios.delete(`${URL}/api/relation/id/${throwaway_id}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation deleted')
    })

    it('the relation is gone after deletion', async () => {
        const gone_id = await findRelationIdByNote('throwaway-relation')
        expect(gone_id).toBeNull()
    })
})
