const { PORT } = require('../core/env')
const URL = `http://localhost:${PORT}`

const axios = require('axios')

const { SYSTEM_ENTITIES, ADMIN_USERNAME, ADMIN_DEFAULT_PASSWORD, SESSION_COOKIE_NAME } = require('../core/constants')
const { readCookie } = require('../core/cookies')
const { verifyToken } = require('../core/jwt')
const { RELATION_TYPES } = require('./types-of-relation')
const relation_repository = require('./repository')
const permission_service = require('../permission/service')
const seeder_service = require('../seeder/service')
const { ADMINISTRATOR_PERMISSION_NAME } = require('../permission/util')

// Every request is read as data, never as an exception, so each test asserts the status code
//  itself instead of branching on a thrown error.
const ANY_STATUS = { validateStatus: () => true }

const SAMPLE = {
    id_1: 100,
    entity_1: 'file',
    id_2: 200,
    entity_2: 'metadata',
    relation_type: 'linked',
    note: 'File 100 linked to metadata 200'
}

const SECOND_SAMPLE = {
    id_1: 100,
    entity_1: 'directory',
    id_2: 300,
    entity_2: 'directory',
    relation_type: 'contains',
    note: 'Directory 100 contains directory 300'
}

// The id is generated by the server, so we look created relations up by their note.
let sample_id = ''
let second_id = ''

async function findRelationIdByNote(note) {
    const res = await axios.get(`${URL}/api/relation/`, { validateStatus: () => true })
    const found = res.data.data.filter(r => r.note === note)
    if (found.length === 0) return null
    // The last match is the one this run created: relations are only ever soft-deleted, so a
    //  note can survive from an earlier run whenever the table was not wiped.
    return found[found.length - 1].id
}

beforeAll(() => {
    relation_repository.deleteAll()

    // The wipe above also removes the admin user -> administrator permission link that the
    //  seeder creates at startup, and nothing re-creates it until the next boot. Calling the
    //  startup function again puts the invariant back, so the authorization block below tests
    //  the real seeded link and the database is left sane for the run after this one.
    seeder_service.linkAdminUser()
})

describe('GET /api/relation/entities/', () => {
    it('returns 200 with the enumerated list of system entities', async () => {
        const res = await axios.get(`${URL}/api/relation/entities/`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        expect(res.data.data).toEqual(SYSTEM_ENTITIES)
    })
})

describe('GET /api/relation/types/', () => {
    it('returns 200 with the fixed list of relation types', async () => {
        const res = await axios.get(`${URL}/api/relation/types/`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        expect(res.data.data).toEqual(RELATION_TYPES)
    })
})

describe('POST /api/relation/', () => {
    it('returns 400 warning on invalid body (id_1 not a number)', async () => {
        const res = await axios.post(`${URL}/api/relation/`, { ...SAMPLE, id_1: '100' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 400 warning on entity not in SYSTEM_ENTITIES', async () => {
        const res = await axios.post(`${URL}/api/relation/`, { ...SAMPLE, entity_1: 'not-a-real-entity' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 400 warning on relation_type not in RELATION_TYPES', async () => {
        const res = await axios.post(`${URL}/api/relation/`, { ...SAMPLE, relation_type: 'not-a-real-type' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 400 warning on missing relation_type', async () => {
        const no_type = { ...SAMPLE }
        delete no_type.relation_type
        const res = await axios.post(`${URL}/api/relation/`, no_type, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 201 on valid relation', async () => {
        const res = await axios.post(`${URL}/api/relation/`, SAMPLE, { validateStatus: () => true })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation created')

        sample_id = await findRelationIdByNote(SAMPLE.note)
        expect(typeof sample_id).toBe('number')
    })

    it('returns 201 on valid relation without note (note is nullable)', async () => {
        const no_note = { ...SECOND_SAMPLE }
        delete no_note.note
        const res = await axios.post(`${URL}/api/relation/`, no_note, { validateStatus: () => true })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')
    })

    it('allows a second relation for the same id_1 and a different id_2 (no uniqueness restriction)', async () => {
        const res = await axios.post(`${URL}/api/relation/`, SECOND_SAMPLE, { validateStatus: () => true })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation created')

        second_id = await findRelationIdByNote(SECOND_SAMPLE.note)
        expect(typeof second_id).toBe('number')
    })
})

describe('GET /api/relation/', () => {
    it('returns 200 with a data array', async () => {
        const res = await axios.get(`${URL}/api/relation/`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
    })
})

describe('GET /api/relation/id/:id', () => {
    it('returns 200 with the relation when found', async () => {
        const res = await axios.get(`${URL}/api/relation/id/${sample_id}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(res.data.data.id).toBe(sample_id)
        expect(res.data.data.entity_1).toBe(SAMPLE.entity_1)
        expect(res.data.data.entity_2).toBe(SAMPLE.entity_2)
        expect(res.data.data.relation_type).toBe(SAMPLE.relation_type)
    })

    it('returns 404 when the id does not exist', async () => {
        const res = await axios.get(`${URL}/api/relation/id/nonexistent-id`, { validateStatus: () => true })
        expect(res.status).toBe(404)
        expect(res.data.status).toBe('failed')
        expect(res.data.description).toBe('relation not found')
    })
})

describe('GET /api/relation/entity/:entity', () => {
    it('returns 200 with relations matching the entity', async () => {
        const res = await axios.get(`${URL}/api/relation/entity/${SAMPLE.entity_1}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        const ids = res.data.data.map(r => r.id)
        expect(ids).toContain(sample_id)
    })

    it('returns 400 warning when entity is not in SYSTEM_ENTITIES', async () => {
        const res = await axios.get(`${URL}/api/relation/entity/not-a-real-entity`, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation entity invalid')
    })
})

describe('GET /api/relation/entity_id/:id', () => {
    it('returns 200 with relations where the record id appears on either side', async () => {
        const res = await axios.get(`${URL}/api/relation/entity_id/${SAMPLE.id_1}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        const ids = res.data.data.map(r => r.id)
        expect(ids).toContain(sample_id)
        expect(ids).toContain(second_id)
    })

    it('returns 200 with empty array when no relation matches', async () => {
        const res = await axios.get(`${URL}/api/relation/entity_id/0`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(Array.isArray(res.data.data)).toBe(true)
        expect(res.data.data.length).toBe(0)
    })
})

describe('PUT /api/relation/update/', () => {
    it('returns 400 warning on invalid body (id_1 not a number)', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, { ...SAMPLE, id: sample_id, id_1: '100' }, { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })

    it('returns 404 when relation does not exist', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, { ...SAMPLE, id: 999999 }, { validateStatus: () => true })
        expect(res.status).toBe(404)
        expect(res.data.status).toBe('failed')
        expect(res.data.description).toBe('relation not found')
    })

    it('returns 200 on valid update (note and relation_type changed)', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, { ...SAMPLE, id: sample_id, relation_type: 'sibling', note: 'Updated note' }, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation updated')

        const get = await axios.get(`${URL}/api/relation/id/${sample_id}`, { validateStatus: () => true })
        expect(get.data.data.note).toBe('Updated note')
        expect(get.data.data.relation_type).toBe('sibling')
    })
})

describe('PUT /api/relation/update/ deleted_at', () => {
    const DELETED_SAMPLE = {
        id_1: 900,
        entity_1: 'file',
        id_2: 901,
        entity_2: 'tag',
        relation_type: 'tagged',
        note: 'trash-relation'
    }

    let target_id = ''

    // Builds the full update body the endpoint expects, adding the deleted_at field only
    //  when the test explicitly passes one.
    const buildBody = (deleted_at) => {
        const body = { ...DELETED_SAMPLE, id: target_id }
        if (deleted_at !== undefined) body.deleted_at = deleted_at
        return body
    }

    const readRelation = async () => {
        const res = await axios.get(`${URL}/api/relation/id/${target_id}`, { validateStatus: () => true })
        return res.data.data
    }

    beforeAll(async () => {
        await axios.post(`${URL}/api/relation/`, DELETED_SAMPLE, { validateStatus: () => true })
        target_id = await findRelationIdByNote(DELETED_SAMPLE.note)
    })

    it('stores null on a newly created relation', async () => {
        const relation = await readRelation()
        expect(relation.deleted_at).toBeNull()
    })

    it('stores the Unix Epoch in seconds when true is sent', async () => {
        const before = Math.floor(Date.now() / 1000)
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(true), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const relation = await readRelation()
        expect(typeof relation.deleted_at).toBe('number')
        expect(relation.deleted_at).toBeGreaterThanOrEqual(before)
        expect(relation.deleted_at).toBeLessThanOrEqual(Math.floor(Date.now() / 1000))
    })

    it('returns deleted relations in the full listing', async () => {
        const res = await axios.get(`${URL}/api/relation/`, { validateStatus: () => true })
        const relation = res.data.data.find(r => r.id === target_id)
        expect(relation).toBeDefined()
        expect(typeof relation.deleted_at).toBe('number')
    })

    it('returns a deleted relation when asked by id', async () => {
        const res = await axios.get(`${URL}/api/relation/id/${target_id}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(typeof res.data.data.deleted_at).toBe('number')
    })

    it('returns a deleted relation when querying by entity', async () => {
        const res = await axios.get(`${URL}/api/relation/entity/${DELETED_SAMPLE.entity_1}`, { validateStatus: () => true })
        const relation = res.data.data.find(r => r.id === target_id)
        expect(relation).toBeDefined()
        expect(typeof relation.deleted_at).toBe('number')
    })

    it('returns a deleted relation when querying by entity id', async () => {
        const res = await axios.get(`${URL}/api/relation/entity_id/${DELETED_SAMPLE.id_1}`, { validateStatus: () => true })
        const relation = res.data.data.find(r => r.id === target_id)
        expect(relation).toBeDefined()
        expect(typeof relation.deleted_at).toBe('number')
    })

    it('keeps the stored value when deleted_at is not sent', async () => {
        const before = await readRelation()
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(undefined), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const after = await readRelation()
        expect(after.deleted_at).toBe(before.deleted_at)
    })

    it('sets a newer Unix Epoch when true is sent on an already deleted relation', async () => {
        const before = await readRelation()
        expect(typeof before.deleted_at).toBe('number')

        // getSystemTime() works in whole seconds, so the clock must advance for the new
        //  value to be distinguishable from the previous one.
        await new Promise(resolve => setTimeout(resolve, 1100))

        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(true), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const after = await readRelation()
        expect(after.deleted_at).toBeGreaterThan(before.deleted_at)
    })

    it('clears the value back to null when false is sent', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(false), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const relation = await readRelation()
        expect(relation.deleted_at).toBeNull()
    })

    it('stays null when false is sent on a relation that was not deleted', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody(false), { validateStatus: () => true })
        expect(res.status).toBe(200)

        const relation = await readRelation()
        expect(relation.deleted_at).toBeNull()
    })

    it('returns 400 warning when deleted_at is not a boolean', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, buildBody('yes'), { validateStatus: () => true })
        expect(res.status).toBe(400)
        expect(res.data.status).toBe('warning')
        expect(res.data.description).toBe('relation invalid')
    })
})

describe('DELETE /api/relation/id/:id (soft-delete)', () => {
    let throwaway_id = ''

    it('stamps deleted_at and keeps the relation readable', async () => {
        // Delete a throwaway relation so the sample relations persist in the database.
        await axios.post(`${URL}/api/relation/`, { ...SAMPLE, note: 'throwaway-relation' }, { validateStatus: () => true })
        throwaway_id = await findRelationIdByNote('throwaway-relation')

        const res = await axios.delete(`${URL}/api/relation/id/${throwaway_id}`, { validateStatus: () => true })
        expect(res.status).toBe(200)
        expect(res.data.status).toBe('success')
        expect(res.data.description).toBe('relation deleted')

        // Soft-deleted: the row stays readable so the client can show it in a trash can.
        const gone = await axios.get(`${URL}/api/relation/id/${throwaway_id}`, { validateStatus: () => true })
        expect(gone.status).toBe(200)
        expect(typeof gone.data.data.deleted_at).toBe('number')

        const list = await axios.get(`${URL}/api/relation/`, { validateStatus: () => true })
        expect(list.data.data.find(r => r.id === throwaway_id)).toBeDefined()
    })

    it('restores the deleted relation through the update endpoint', async () => {
        const res = await axios.put(`${URL}/api/relation/update/`, { ...SAMPLE, id: throwaway_id, note: 'throwaway-relation', deleted_at: false }, { validateStatus: () => true })
        expect(res.status).toBe(200)

        const restored = await axios.get(`${URL}/api/relation/id/${throwaway_id}`, { validateStatus: () => true })
        expect(restored.data.data.deleted_at).toBeNull()
    })
})

// --------------------------------------------------------------------------------
// Tag associations.
//
// A tag is attached to the rest of the system through this entity and nothing else:
// there is no tag column on file, directory or anything. That makes these tests
// relation tests, even though the record on the other side is always a tag.
//
// There is one block per name in SYSTEM_ENTITIES, and every block drives the six
// routes of tag/routes.js while a live relation points at the tag. The point is the
// stress: renaming a tag, soft-deleting it or changing the entity catalogue must
// break these tests loudly instead of silently leaving a dangling association.
// --------------------------------------------------------------------------------

// The scaffolding tags carry a per-run suffix. Tag names are UNIQUE and this file must not
//  wipe another entity's table, so the suffix is what keeps the names free on every run,
//  whatever has run before.
const RUN = Date.now()

// One wrapper per route in tag/routes.js. The tag entity is reached only through its own HTTP
//  surface here, never through its internals.
const tagGetAll = () => axios.get(`${URL}/api/tag/`, ANY_STATUS)
const tagGetById = (id) => axios.get(`${URL}/api/tag/id/${id}`, ANY_STATUS)
const tagGetByName = (name) => axios.get(`${URL}/api/tag/name/${encodeURIComponent(name)}`, ANY_STATUS)
const tagPost = (body) => axios.post(`${URL}/api/tag/`, body, ANY_STATUS)
const tagUpdate = (body) => axios.put(`${URL}/api/tag/update/`, body, ANY_STATUS)
const tagDelete = (id) => axios.delete(`${URL}/api/tag/id/${id}`, ANY_STATUS)

const relationPost = (body) => axios.post(`${URL}/api/relation/`, body, ANY_STATUS)
const relationGetById = (id) => axios.get(`${URL}/api/relation/id/${id}`, ANY_STATUS)
const relationGetByEntity = (entity) => axios.get(`${URL}/api/relation/entity/${entity}`, ANY_STATUS)
const relationGetByEntityId = (id) => axios.get(`${URL}/api/relation/entity_id/${id}`, ANY_STATUS)
const relationDelete = (id) => axios.delete(`${URL}/api/relation/id/${id}`, ANY_STATUS)

// One wrapper per permission route the blocks below need (the "permission x tag" block and the
//  "user x permission" block further down). Like every other entity here, permission is reached
//  only through its own HTTP surface, never through its internals.
const permissionPost = (body) => axios.post(`${URL}/api/permission/`, body, ANY_STATUS)
const permissionGetById = (id) => axios.get(`${URL}/api/permission/id/${id}`, ANY_STATUS)
const permissionGetByName = (name) => axios.get(`${URL}/api/permission/name/${encodeURIComponent(name)}`, ANY_STATUS)
const permissionUpdate = (body) => axios.put(`${URL}/api/permission/update/`, body, ANY_STATUS)
const permissionDelete = (id) => axios.delete(`${URL}/api/permission/id/${id}`, ANY_STATUS)

// One wrapper per route in workspace/routes.js. Like every other entity here, workspace is
//  reached only through its own HTTP surface, never through its internals.
const workspacePost = (body) => axios.post(`${URL}/api/workspace/`, body, ANY_STATUS)
const workspaceGetAll = () => axios.get(`${URL}/api/workspace/`, ANY_STATUS)
const workspaceGetById = (id) => axios.get(`${URL}/api/workspace/id/${id}`, ANY_STATUS)
const workspaceUpdate = (body) => axios.put(`${URL}/api/workspace/update/`, body, ANY_STATUS)
const workspaceDelete = (id) => axios.delete(`${URL}/api/workspace/id/${id}`, ANY_STATUS)

describe('System entity catalogue coverage', () => {
    // Guard for the blocks below: each entity of the catalogue has its own block. When an
    //  entity is added, removed or renamed in SYSTEM_ENTITIES this test fails, as a reminder
    //  to write (or retire) the matching block instead of silently losing the coverage.
    // permission is covered twice on purpose: the "permission x tag" block proves nothing
    //  restricts it from being tagged like any other catalogue entity (portability first, even
    //  though the GUI may end up never exposing that combination), and the "user x permission"
    //  block covers the real authorization link, which is what a permission is actually used for.
    const TAG_COVERED_ENTITIES = ['directory', 'file', 'metadata', 'permission', 'relation', 'tag', 'user', 'workspace']

    it('SYSTEM_ENTITIES holds exactly the entities covered by the blocks below', () => {
        expect([...SYSTEM_ENTITIES].sort()).toEqual([...TAG_COVERED_ENTITIES].sort())
    })

    it('offers the relation types the blocks below use', async () => {
        const res = await axios.get(`${URL}/api/relation/types/`, ANY_STATUS)
        expect(res.status).toBe(200)
        expect(res.data.data).toContain('tagged')
        expect(res.data.data).toContain('implies')
        expect(res.data.data).toContain('linked')
    })
})

describe('directory x tag — the six tag routes with a live relation', () => {
    const TAG = { name: `rel-directory-${RUN}`, metadata: '{"related_to":"directory"}' }
    const RENAMED = `rel-directory-renamed-${RUN}`
    const NOTE = `relation-test: directory <-> tag ${RUN}`

    const DIRECTORY_NAME = `rel-directory-${RUN}`

    let tag_id = ''
    let directory_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: the directory only exists to be the other side of the relation.
        await axios.post(`${URL}/api/directory/`, { name: DIRECTORY_NAME }, ANY_STATUS)
        const directories = await axios.get(`${URL}/api/directory/`, ANY_STATUS)
        directory_id = directories.data.data.find(d => d.name === DIRECTORY_NAME).id
    })

    it('POST /api/tag/ creates the tag the directory will be tagged with', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates the directory to the tag with a "tagged" relation', async () => {
        const res = await relationPost({
            id_1: directory_id,
            entity_1: 'directory',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'tagged',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists the related tag', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves the tag the relation points at', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('directory')
        expect(relation.data.data.entity_2).toBe('tag')

        const res = await tagGetById(relation.data.data.id_2)
        expect(res.status).toBe(200)
        expect(res.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the tag without breaking the relation', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the tag and the relation still resolves it', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        const tag = await tagGetById(relation.data.data.id_2)
        expect(tag.status).toBe(200)
        expect(typeof tag.data.data.deleted_at).toBe('number')
    })

    it('GET /api/relation/entity/directory still lists the relation', async () => {
        const res = await relationGetByEntity('directory')
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    it('GET /api/relation/entity_id/:id finds the relation from the directory side', async () => {
        const res = await relationGetByEntityId(directory_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    afterAll(async () => {
        await relationDelete(relation_id)
        await axios.delete(`${URL}/api/directory/id/${directory_id}`, ANY_STATUS)
    })
})

describe('file x tag — the six tag routes with a live relation', () => {
    const TAG = { name: `rel-file-${RUN}`, metadata: '{"related_to":"file"}' }
    const RENAMED = `rel-file-renamed-${RUN}`
    const NOTE = `relation-test: file <-> tag ${RUN}`
    const HASH = `rel-file-hash-${RUN}`

    let tag_id = ''
    let file_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: the file only exists to be the other side of the relation.
        await axios.post(`${URL}/api/file/`, {
            name: 'rel-file.png',
            hash_256_sha: HASH,
            relative_path: '/rel/rel-file.png',
            extension: 'png'
        }, ANY_STATUS)
        const files = await axios.get(`${URL}/api/file/`, ANY_STATUS)
        file_id = files.data.data.find(f => f.hash_256_sha === HASH).id
    })

    it('POST /api/tag/ creates the tag the file will be tagged with', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates the file to the tag with a "tagged" relation', async () => {
        const res = await relationPost({
            id_1: file_id,
            entity_1: 'file',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'tagged',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists the related tag', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves the tag the relation points at', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('file')
        expect(relation.data.data.entity_2).toBe('tag')

        const res = await tagGetById(relation.data.data.id_2)
        expect(res.status).toBe(200)
        expect(res.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the tag without breaking the relation', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the tag and the relation still resolves it', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        const tag = await tagGetById(relation.data.data.id_2)
        expect(tag.status).toBe(200)
        expect(typeof tag.data.data.deleted_at).toBe('number')
    })

    it('GET /api/relation/entity_id/:id finds the relation from the file side', async () => {
        const res = await relationGetByEntityId(file_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    afterAll(async () => {
        await relationDelete(relation_id)
        await axios.delete(`${URL}/api/file/id/${file_id}`, ANY_STATUS)
    })
})

describe('metadata x tag — the six tag routes with a live relation', () => {
    const TAG = { name: `rel-metadata-${RUN}`, metadata: '{"related_to":"metadata"}' }
    const RENAMED = `rel-metadata-renamed-${RUN}`
    const NOTE = `relation-test: metadata <-> tag ${RUN}`
    const KEY = `rel_metadata_key_${RUN}`

    let tag_id = ''
    let metadata_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: the metadata record only exists to be the other side of the relation.
        await axios.post(`${URL}/api/metadata/`, { name: KEY, value: 'related to a tag' }, ANY_STATUS)
        const res = await axios.get(`${URL}/api/metadata/name/${KEY}`, ANY_STATUS)
        metadata_id = res.data.data.id
    })

    it('POST /api/tag/ creates the tag linked to the metadata record', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates the metadata record to the tag with a "linked" relation', async () => {
        const res = await relationPost({
            id_1: metadata_id,
            entity_1: 'metadata',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'linked',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists the related tag', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves the tag the relation points at', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('metadata')
        expect(relation.data.data.entity_2).toBe('tag')

        const res = await tagGetById(relation.data.data.id_2)
        expect(res.status).toBe(200)
        expect(res.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the tag without breaking the relation', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the tag and the relation still resolves it', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        const tag = await tagGetById(relation.data.data.id_2)
        expect(tag.status).toBe(200)
        expect(typeof tag.data.data.deleted_at).toBe('number')
    })

    it('keeps the link readable after the metadata record is soft-deleted too', async () => {
        // Both sides in the trash can: the relation is still there and still resolves.
        await axios.delete(`${URL}/api/metadata/name/${KEY}`, ANY_STATUS)

        const relation = await relationGetById(relation_id)
        expect(relation.status).toBe(200)

        const metadata = await axios.get(`${URL}/api/metadata/id/${relation.data.data.id_1}`, ANY_STATUS)
        expect(metadata.status).toBe(200)
        expect(typeof metadata.data.data.deleted_at).toBe('number')
    })

    afterAll(async () => {
        await relationDelete(relation_id)
    })
})

describe('permission x tag — the six tag routes with a live relation', () => {
    // This is not the authorization link (a permission is granted to a user through a "linked"
    //  relation, covered by the "user x permission" block further down). Nothing in
    //  SYSTEM_ENTITIES, RELATION_TYPES or the validators singles permission out, so it can be
    //  tagged like any other catalogue entity — this block proves it, for portability, even if
    //  the GUI never ends up exposing the combination.
    const TAG = { name: `rel-permission-${RUN}`, metadata: '{"related_to":"permission"}' }
    const RENAMED = `rel-permission-renamed-${RUN}`
    const NOTE = `relation-test: permission <-> tag ${RUN}`

    const PERMISSION_NAME = `rel-permission-${RUN}`

    let tag_id = ''
    let permission_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: the permission only exists to be the other side of the relation.
        await permissionPost({ name: PERMISSION_NAME, can_read: false, can_create: false, can_edit: false, can_delete: false })
        const created = await permissionGetByName(PERMISSION_NAME)
        permission_id = created.data.data.id
    })

    it('POST /api/tag/ creates the tag the permission will be tagged with', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates the permission to the tag with a "tagged" relation', async () => {
        const res = await relationPost({
            id_1: permission_id,
            entity_1: 'permission',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'tagged',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists the related tag', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves the tag the relation points at', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('permission')
        expect(relation.data.data.entity_2).toBe('tag')

        const res = await tagGetById(relation.data.data.id_2)
        expect(res.status).toBe(200)
        expect(res.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the tag without breaking the relation', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the tag and the relation still resolves it', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        const tag = await tagGetById(relation.data.data.id_2)
        expect(tag.status).toBe(200)
        expect(typeof tag.data.data.deleted_at).toBe('number')
    })

    it('GET /api/relation/entity/permission still lists the relation', async () => {
        const res = await relationGetByEntity('permission')
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    it('GET /api/relation/entity_id/:id finds the relation from the permission side', async () => {
        const res = await relationGetByEntityId(permission_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    afterAll(async () => {
        await relationDelete(relation_id)
        await permissionDelete(permission_id)
    })
})

describe('workspace x tag — the six tag routes with a live relation', () => {
    const TAG = { name: `rel-workspace-${RUN}`, metadata: '{"related_to":"workspace"}' }
    const RENAMED = `rel-workspace-renamed-${RUN}`
    const NOTE = `relation-test: workspace <-> tag ${RUN}`

    const WORKSPACE = { name: `rel-workspace-${RUN}`, path_absolute: `/rel-workspace-${RUN}/`, path_relative: `rel-workspace-${RUN}` }

    let tag_id = ''
    let workspace_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: the workspace only exists to be the other side of the relation.
        await workspacePost(WORKSPACE)
        const workspaces = await workspaceGetAll()
        workspace_id = workspaces.data.data.find(w => w.path_absolute === WORKSPACE.path_absolute).id
    })

    it('POST /api/tag/ creates the tag the workspace will be tagged with', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates the workspace to the tag with a "tagged" relation', async () => {
        const res = await relationPost({
            id_1: workspace_id,
            entity_1: 'workspace',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'tagged',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists the related tag', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves the tag the relation points at', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('workspace')
        expect(relation.data.data.entity_2).toBe('tag')

        const res = await tagGetById(relation.data.data.id_2)
        expect(res.status).toBe(200)
        expect(res.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the tag without breaking the relation', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the tag and the relation still resolves it', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        const tag = await tagGetById(relation.data.data.id_2)
        expect(tag.status).toBe(200)
        expect(typeof tag.data.data.deleted_at).toBe('number')
    })

    it('GET /api/relation/entity/workspace still lists the relation', async () => {
        const res = await relationGetByEntity('workspace')
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    it('GET /api/relation/entity_id/:id finds the relation from the workspace side', async () => {
        const res = await relationGetByEntityId(workspace_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    afterAll(async () => {
        await relationDelete(relation_id)
        await workspaceDelete(workspace_id)
    })
})

describe('metadata x workspace — a direct relation between two non-tag entities', () => {
    // This is the pairing the WorkSpace entity exists for in the first place: which absolute
    //  directories the file system manager may work in is stored as a workspace record, and a
    //  metadata key/value can point at one directly, exactly like the "directory x file"
    //  hierarchy above proves two non-tag entities can be related without going through tag.
    const KEY = `rel_metadata_workspace_key_${RUN}`
    const WORKSPACE = { name: `rel-metadata-workspace-${RUN}`, path_absolute: `/rel-metadata-workspace-${RUN}/`, path_relative: `rel-metadata-workspace-${RUN}` }
    const NOTE = `relation-test: metadata <-> workspace ${RUN}`

    let metadata_id = ''
    let workspace_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: a metadata record and a workspace record, each only existing to be one
        //  side of the relation.
        await axios.post(`${URL}/api/metadata/`, { name: KEY, value: WORKSPACE.path_absolute }, ANY_STATUS)
        const metadata = await axios.get(`${URL}/api/metadata/name/${KEY}`, ANY_STATUS)
        metadata_id = metadata.data.data.id

        await workspacePost(WORKSPACE)
        const workspaces = await workspaceGetAll()
        workspace_id = workspaces.data.data.find(w => w.path_absolute === WORKSPACE.path_absolute).id
    })

    it('the scaffolding records exist on both sides', () => {
        expect(typeof metadata_id).toBe('number')
        expect(typeof workspace_id).toBe('number')
    })

    it('relates the metadata record to the workspace with a "linked" relation', async () => {
        const res = await relationPost({
            id_1: metadata_id,
            entity_1: 'metadata',
            id_2: workspace_id,
            entity_2: 'workspace',
            relation_type: 'linked',
            note: NOTE
        })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('stores the metadata record as id_1 and the workspace as id_2', async () => {
        const res = await relationGetById(relation_id)
        expect(res.status).toBe(200)
        expect(res.data.data.entity_1).toBe('metadata')
        expect(res.data.data.id_1).toBe(metadata_id)
        expect(res.data.data.entity_2).toBe('workspace')
        expect(res.data.data.id_2).toBe(workspace_id)
    })

    it('resolves both sides of the relation through their own routes', async () => {
        const relation = await relationGetById(relation_id)

        const metadata = await axios.get(`${URL}/api/metadata/id/${relation.data.data.id_1}`, ANY_STATUS)
        expect(metadata.status).toBe(200)
        expect(metadata.data.data.name).toBe(KEY)

        const workspace = await workspaceGetById(relation.data.data.id_2)
        expect(workspace.status).toBe(200)
        expect(workspace.data.data.path_absolute).toBe(WORKSPACE.path_absolute)
    })

    it('GET /api/relation/entity/:entity lists it from both entity names', async () => {
        const from_metadata = await relationGetByEntity('metadata')
        expect(from_metadata.status).toBe(200)
        expect(from_metadata.data.data.find(r => r.id === relation_id)).toBeDefined()

        const from_workspace = await relationGetByEntity('workspace')
        expect(from_workspace.status).toBe(200)
        expect(from_workspace.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    it('GET /api/relation/entity_id/:id finds it from either side', async () => {
        const from_metadata = await relationGetByEntityId(metadata_id)
        expect(from_metadata.data.data.find(r => r.id === relation_id)).toBeDefined()

        const from_workspace = await relationGetByEntityId(workspace_id)
        expect(from_workspace.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    it('keeps the link readable after the metadata record is soft-deleted', async () => {
        await axios.delete(`${URL}/api/metadata/name/${KEY}`, ANY_STATUS)

        const relation = await relationGetById(relation_id)
        expect(relation.status).toBe(200)

        const metadata = await axios.get(`${URL}/api/metadata/id/${relation.data.data.id_1}`, ANY_STATUS)
        expect(metadata.status).toBe(200)
        expect(typeof metadata.data.data.deleted_at).toBe('number')
    })

    it('keeps the link readable after the workspace is soft-deleted too', async () => {
        await workspaceDelete(workspace_id)

        const relation = await relationGetById(relation_id)
        expect(relation.status).toBe(200)

        const workspace = await workspaceGetById(relation.data.data.id_2)
        expect(workspace.status).toBe(200)
        expect(typeof workspace.data.data.deleted_at).toBe('number')
    })

    afterAll(async () => {
        await relationDelete(relation_id)
    })
})

describe('relation x tag — the six tag routes with a live relation', () => {
    const TAG = { name: `rel-relation-${RUN}`, metadata: '{"related_to":"relation"}' }
    const RENAMED = `rel-relation-renamed-${RUN}`
    const NOTE = `relation-test: relation <-> tag ${RUN}`
    const SCAFFOLDING_NOTE = `relation-test: relation record used as the other side ${RUN}`

    let tag_id = ''
    let related_relation_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: a relation record that the tag will be linked to. A relation is an
        //  entity of the catalogue like any other, so it can sit on the other side of a link.
        await relationPost({
            id_1: 1,
            entity_1: 'file',
            id_2: 1,
            entity_2: 'file',
            relation_type: 'sibling',
            note: SCAFFOLDING_NOTE
        })
        related_relation_id = await findRelationIdByNote(SCAFFOLDING_NOTE)
    })

    it('POST /api/tag/ creates the tag linked to the relation record', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates the relation record to the tag with a "linked" relation', async () => {
        const res = await relationPost({
            id_1: related_relation_id,
            entity_1: 'relation',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'linked',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists the related tag', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves the tag the relation points at', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('relation')
        expect(relation.data.data.entity_2).toBe('tag')

        const res = await tagGetById(relation.data.data.id_2)
        expect(res.status).toBe(200)
        expect(res.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the tag without breaking the relation', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the tag and the relation still resolves it', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        const tag = await tagGetById(relation.data.data.id_2)
        expect(tag.status).toBe(200)
        expect(typeof tag.data.data.deleted_at).toBe('number')
    })

    it('reaches the tagged relation record from the link', async () => {
        const relation = await relationGetById(relation_id)
        const target = await relationGetById(relation.data.data.id_1)
        expect(target.status).toBe(200)
        expect(target.data.data.note).toBe(SCAFFOLDING_NOTE)
    })

    afterAll(async () => {
        await relationDelete(relation_id)
        await relationDelete(related_relation_id)
    })
})

describe('tag x tag — the six tag routes with a live relation', () => {
    const TAG = { name: `rel-tag-${RUN}`, metadata: '{"related_to":"tag"}' }
    const ANTECEDENT = { name: `rel-tag-antecedent-${RUN}`, metadata: '{}' }
    const RENAMED = `rel-tag-renamed-${RUN}`
    const NOTE = `relation-test: tag <-> tag ${RUN}`

    let tag_id = ''
    let antecedent_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // Scaffolding: the antecedent of the implication. Both sides of an "implies" relation
        //  are always tags (Danbooru style: antecedent id_1 implies consequent id_2).
        await tagPost(ANTECEDENT)
        const res = await tagGetByName(ANTECEDENT.name)
        antecedent_id = res.data.data.id
    })

    it('POST /api/tag/ creates the consequent tag', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates one tag to the other with an "implies" relation', async () => {
        const res = await relationPost({
            id_1: antecedent_id,
            entity_1: 'tag',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'implies',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists both sides of the implication', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
        expect(res.data.data.find(t => t.id === antecedent_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves both ends of the relation', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('tag')
        expect(relation.data.data.entity_2).toBe('tag')

        const antecedent = await tagGetById(relation.data.data.id_1)
        expect(antecedent.status).toBe(200)
        expect(antecedent.data.data.name).toBe(ANTECEDENT.name)

        const consequent = await tagGetById(relation.data.data.id_2)
        expect(consequent.status).toBe(200)
        expect(consequent.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the consequent without breaking the implication', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_1).toBe(antecedent_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the consequent and the antecedent stays untouched', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)

        const consequent = await tagGetById(relation.data.data.id_2)
        expect(typeof consequent.data.data.deleted_at).toBe('number')

        const antecedent = await tagGetById(relation.data.data.id_1)
        expect(antecedent.data.data.deleted_at).toBeNull()
    })

    it('GET /api/relation/entity_id/:id finds the implication from the antecedent', async () => {
        const res = await relationGetByEntityId(antecedent_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    afterAll(async () => {
        await relationDelete(relation_id)
    })
})

describe('user x tag — the six tag routes with a live relation', () => {
    const TAG = { name: `rel-user-${RUN}`, metadata: '{"related_to":"user"}' }
    const RENAMED = `rel-user-renamed-${RUN}`
    const NOTE = `relation-test: user <-> tag ${RUN}`

    let tag_id = ''
    let user_id = ''
    let relation_id = ''

    beforeAll(async () => {
        // No endpoint returns a user id: it travels inside the session token. Logging in as
        //  the seeded admin and reading the cookie is the only way to it through the public
        //  surface, and it breaks loudly if the session ever stops carrying { id }.
        const login = await axios.post(`${URL}/api/user/login/`, {
            username: ADMIN_USERNAME,
            password: ADMIN_DEFAULT_PASSWORD
        }, ANY_STATUS)
        const token = readCookie(login.headers['set-cookie'][0], SESSION_COOKIE_NAME)
        user_id = verifyToken(token).id
    })

    it('resolves the admin user id out of the session cookie', () => {
        expect(typeof user_id).toBe('number')
    })

    it('POST /api/tag/ creates the tag linked to the user', async () => {
        const res = await tagPost(TAG)
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        const created = await tagGetByName(TAG.name)
        tag_id = created.data.data.id
        expect(typeof tag_id).toBe('number')
    })

    it('relates the user to the tag with a "linked" relation', async () => {
        const res = await relationPost({
            id_1: user_id,
            entity_1: 'user',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'linked',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('GET /api/tag/ lists the related tag', async () => {
        const res = await tagGetAll()
        expect(res.status).toBe(200)
        expect(res.data.data.find(t => t.id === tag_id)).toBeDefined()
    })

    it('GET /api/tag/id/:id resolves the tag the relation points at', async () => {
        const relation = await relationGetById(relation_id)
        expect(relation.data.data.entity_1).toBe('user')
        expect(relation.data.data.entity_2).toBe('tag')

        const res = await tagGetById(relation.data.data.id_2)
        expect(res.status).toBe(200)
        expect(res.data.data.name).toBe(TAG.name)
    })

    it('GET /api/tag/name/:name resolves the same tag, whatever the case', async () => {
        const res = await tagGetByName(TAG.name.toUpperCase())
        expect(res.status).toBe(200)
        expect(res.data.data.id).toBe(tag_id)
    })

    it('PUT /api/tag/update/ renames the tag without breaking the relation', async () => {
        const res = await tagUpdate({ id: tag_id, name: RENAMED, metadata: TAG.metadata })
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        expect(relation.data.data.id_2).toBe(tag_id)

        const renamed = await tagGetById(relation.data.data.id_2)
        expect(renamed.data.data.name).toBe(RENAMED)
    })

    it('DELETE /api/tag/id/:id soft-deletes the tag and the relation still resolves it', async () => {
        const res = await tagDelete(tag_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(relation_id)
        const tag = await tagGetById(relation.data.data.id_2)
        expect(tag.status).toBe(200)
        expect(typeof tag.data.data.deleted_at).toBe('number')
    })

    it('GET /api/relation/entity/user still lists the relation', async () => {
        const res = await relationGetByEntity('user')
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    afterAll(async () => {
        await relationDelete(relation_id)
    })
})

// --------------------------------------------------------------------------------
// Directory x file associations.
//
// A directory holds nothing: there is no file_id column on directory, and no
// directory_id column on file. What a directory contains, and what sits next to what,
// is a relation record and nothing else — which is why the hierarchy of the file
// system is tested here and not in directory.test.js.
//
// - contains : directional. The directory is always id_1, the thing inside is id_2.
// - sibling  : symmetric. Both records share the same parent directory.
//
// Both entities are reached only through their own HTTP surface, never through their
// internals, exactly like the tag blocks above.
// --------------------------------------------------------------------------------

const directoryPost = (body) => axios.post(`${URL}/api/directory/`, body, ANY_STATUS)
const directoryGetAll = () => axios.get(`${URL}/api/directory/`, ANY_STATUS)
const directoryGetById = (id) => axios.get(`${URL}/api/directory/id/${id}`, ANY_STATUS)
const directoryDelete = (id) => axios.delete(`${URL}/api/directory/id/${id}`, ANY_STATUS)

const filePost = (body) => axios.post(`${URL}/api/file/`, body, ANY_STATUS)
const fileGetAll = () => axios.get(`${URL}/api/file/`, ANY_STATUS)
const fileGetById = (id) => axios.get(`${URL}/api/file/id/${id}`, ANY_STATUS)
const fileDelete = (id) => axios.delete(`${URL}/api/file/id/${id}`, ANY_STATUS)

describe('directory x file — "contains" and "sibling" relations', () => {
    // The scaffolding of this block: one parent directory holding a file, and a second
    //  directory sitting next to that file inside the same parent. The names carry the
    //  per-run suffix of the tag blocks, so the block finds its own rows whatever an
    //  earlier run left behind.
    const PARENT_NAME = `rel-parent-directory-${RUN}`
    const SIBLING_NAME = `rel-sibling-directory-${RUN}`
    const FILE_HASH = `rel-directory-file-hash-${RUN}`

    const CONTAINS_NOTE = `relation-test: directory contains file ${RUN}`
    const SIBLING_NOTE = `relation-test: directory sibling file ${RUN}`

    let parent_id = ''
    let sibling_id = ''
    let file_id = ''
    let contains_id = ''
    let sibling_relation_id = ''

    beforeAll(async () => {
        await directoryPost({ name: PARENT_NAME })
        await directoryPost({ name: SIBLING_NAME })
        await filePost({
            name: 'rel-directory-file.txt',
            hash_256_sha: FILE_HASH,
            relative_path: `/rel/${PARENT_NAME}/rel-directory-file.txt`,
            extension: 'txt'
        })

        const directories = await directoryGetAll()
        parent_id = directories.data.data.find(d => d.name === PARENT_NAME).id
        sibling_id = directories.data.data.find(d => d.name === SIBLING_NAME).id

        const files = await fileGetAll()
        file_id = files.data.data.find(f => f.hash_256_sha === FILE_HASH).id
    })

    it('the scaffolding records exist on both sides', async () => {
        expect(typeof parent_id).toBe('number')
        expect(typeof sibling_id).toBe('number')
        expect(typeof file_id).toBe('number')
    })

    it('relates the parent directory to the file with a "contains" relation', async () => {
        const res = await relationPost({
            id_1: parent_id,
            entity_1: 'directory',
            id_2: file_id,
            entity_2: 'file',
            relation_type: 'contains',
            note: CONTAINS_NOTE
        })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        contains_id = await findRelationIdByNote(CONTAINS_NOTE)
        expect(typeof contains_id).toBe('number')
    })

    it('relates the second directory to the file with a "sibling" relation', async () => {
        const res = await relationPost({
            id_1: sibling_id,
            entity_1: 'directory',
            id_2: file_id,
            entity_2: 'file',
            relation_type: 'sibling',
            note: SIBLING_NOTE
        })
        expect(res.status).toBe(201)
        expect(res.data.status).toBe('success')

        sibling_relation_id = await findRelationIdByNote(SIBLING_NOTE)
        expect(typeof sibling_relation_id).toBe('number')
    })

    it('stores the containment with the directory as id_1 and the file as id_2', async () => {
        const res = await relationGetById(contains_id)
        expect(res.status).toBe(200)
        expect(res.data.data.relation_type).toBe('contains')
        expect(res.data.data.entity_1).toBe('directory')
        expect(res.data.data.id_1).toBe(parent_id)
        expect(res.data.data.entity_2).toBe('file')
        expect(res.data.data.id_2).toBe(file_id)
    })

    it('stores the sibling link between the same two entities', async () => {
        const res = await relationGetById(sibling_relation_id)
        expect(res.status).toBe(200)
        expect(res.data.data.relation_type).toBe('sibling')
        expect(res.data.data.entity_1).toBe('directory')
        expect(res.data.data.id_1).toBe(sibling_id)
        expect(res.data.data.entity_2).toBe('file')
        expect(res.data.data.id_2).toBe(file_id)
    })

    it('resolves both sides of the containment through their own routes', async () => {
        const relation = await relationGetById(contains_id)

        const directory = await directoryGetById(relation.data.data.id_1)
        expect(directory.status).toBe(200)
        expect(directory.data.data.name).toBe(PARENT_NAME)

        const file = await fileGetById(relation.data.data.id_2)
        expect(file.status).toBe(200)
        expect(file.data.data.hash_256_sha).toBe(FILE_HASH)
    })

    it('GET /api/relation/entity_id/:id lists both relations from the file side', async () => {
        const res = await relationGetByEntityId(file_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === contains_id)).toBeDefined()
        expect(res.data.data.find(r => r.id === sibling_relation_id)).toBeDefined()
    })

    it('GET /api/relation/entity_id/:id lists only the containment from the parent side', async () => {
        const res = await relationGetByEntityId(parent_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === contains_id)).toBeDefined()

        // The route matches on the id alone, whatever entity owns it: each table has its own
        //  INTEGER PRIMARY KEY sequence, so a directory id and a file id collide as a matter of
        //  course and the sibling link surfaces here through the file on its other side. What
        //  the parent is really not part of is the sibling link *as a directory*, which is what
        //  this asserts — matching on the bare id would only pass while the ids happened to differ.
        const sibling_from_parent = res.data.data.find(r =>
            r.id === sibling_relation_id && r.entity_1 === 'directory' && r.id_1 === parent_id
        )
        expect(sibling_from_parent).toBeUndefined()
    })

    it('GET /api/relation/entity/:entity lists them from both entity names', async () => {
        const from_directory = await relationGetByEntity('directory')
        expect(from_directory.status).toBe(200)
        expect(from_directory.data.data.find(r => r.id === contains_id)).toBeDefined()
        expect(from_directory.data.data.find(r => r.id === sibling_relation_id)).toBeDefined()

        const from_file = await relationGetByEntity('file')
        expect(from_file.status).toBe(200)
        expect(from_file.data.data.find(r => r.id === contains_id)).toBeDefined()
        expect(from_file.data.data.find(r => r.id === sibling_relation_id)).toBeDefined()
    })

    it('DELETE /api/directory/id/:id soft-deletes the parent and the containment still resolves it', async () => {
        const res = await directoryDelete(parent_id)
        expect(res.status).toBe(200)

        const relation = await relationGetById(contains_id)
        expect(relation.data.data.deleted_at).toBeNull()

        const directory = await directoryGetById(relation.data.data.id_1)
        expect(directory.status).toBe(200)
        expect(typeof directory.data.data.deleted_at).toBe('number')
    })

    it('DELETE /api/file/id/:id soft-deletes the file and both relations still resolve it', async () => {
        const res = await fileDelete(file_id)
        expect(res.status).toBe(200)

        const contains = await relationGetById(contains_id)
        const sibling = await relationGetById(sibling_relation_id)
        expect(contains.data.data.id_2).toBe(file_id)
        expect(sibling.data.data.id_2).toBe(file_id)

        const file = await fileGetById(file_id)
        expect(file.status).toBe(200)
        expect(typeof file.data.data.deleted_at).toBe('number')
    })

    afterAll(async () => {
        await relationDelete(contains_id)
        await relationDelete(sibling_relation_id)
        await directoryDelete(sibling_id)
    })
})

// --------------------------------------------------------------------------------
// User x permission associations.
//
// What a user is allowed to do is a permission record, and the two are joined by a
// relation of type "linked" — the user is id_1, the permission is id_2. There is no
// permission_id column on user, so the whole authorization chain is a relation and
// belongs in this file.
//
// These tests reach permission/service.can() directly, which no other block does.
// The HTTP surface cannot show it: the authorize(verb) guard exists in
// web/middleware.js but no route lists it yet, so the resolution is only observable
// from the backend side. What is asserted is exactly what the guard will ask.
//
// This is the real authorization link. It is separate from the "permission x tag" block
// above, which only proves a permission is not exempt from being related to a tag.
// --------------------------------------------------------------------------------

describe('user x permission — the link that grants rights', () => {
    const PERMISSION_NAME = `rel-user-permission-${RUN}`
    const RENAMED_PERMISSION = `rel-user-permission-renamed-${RUN}`
    const SECOND_PERMISSION_NAME = `rel-user-permission-second-${RUN}`
    const TAG_NAME = `rel-user-permission-tag-${RUN}`

    const NOTE = `relation-test: user <-> permission ${RUN}`
    const SECOND_NOTE = `relation-test: second user <-> permission ${RUN}`
    const DISTRACTION_NOTE = `relation-test: user <-> tag, not a permission ${RUN}`

    // Two user ids that no account owns. Nothing in the chain requires the user row to exist:
    //  the link is resolved from the relation table, so a synthetic id is enough to drive the
    //  rules without touching the seeded admin account, which the block above already uses.
    const USER_ID = 900001
    const SECOND_USER_ID = 900002

    let admin_user_id = ''
    let permission_id = ''
    let second_permission_id = ''
    let tag_id = ''
    let relation_id = ''
    let second_relation_id = ''
    let distraction_id = ''

    // Every right denied. It is the answer for a user with no link, with a trashed link and
    //  with a trashed permission, and each of those is asserted separately below.
    const expectEverythingDenied = (user_id) => {
        expect(permission_service.can(user_id, 'read')).toBe(false)
        expect(permission_service.can(user_id, 'create')).toBe(false)
        expect(permission_service.can(user_id, 'edit')).toBe(false)
        expect(permission_service.can(user_id, 'delete')).toBe(false)
    }

    // The update endpoint replaces the whole record, so changing one field means sending the
    //  others back untouched. These two rebuild the body from the stored row.
    const updateRelation = async (id, changes) => {
        const current = await relationGetById(id)
        const relation = current.data.data
        return axios.put(`${URL}/api/relation/update/`, {
            id: relation.id,
            id_1: relation.id_1,
            entity_1: relation.entity_1,
            id_2: relation.id_2,
            entity_2: relation.entity_2,
            relation_type: relation.relation_type,
            note: relation.note,
            ...changes
        }, ANY_STATUS)
    }

    const updatePermission = async (id, changes) => {
        const current = await permissionGetById(id)
        const permission = current.data.data
        return permissionUpdate({
            id: permission.id,
            name: permission.name,
            can_read: permission.can_read,
            can_create: permission.can_create,
            can_edit: permission.can_edit,
            can_delete: permission.can_delete,
            ...changes
        })
    }

    beforeAll(async () => {
        // No endpoint returns a user id: it travels inside the session token, so logging in as
        //  the seeded admin and reading the cookie is the only way to it through the public
        //  surface.
        const login = await axios.post(`${URL}/api/user/login/`, {
            username: ADMIN_USERNAME,
            password: ADMIN_DEFAULT_PASSWORD
        }, ANY_STATUS)
        const token = readCookie(login.headers['set-cookie'][0], SESSION_COOKIE_NAME)
        admin_user_id = verifyToken(token).id
    })

    // ----------------------------------------------------------------------------
    // The link seeded at startup.
    // ----------------------------------------------------------------------------

    it('resolves the admin user id out of the session cookie', () => {
        expect(typeof admin_user_id).toBe('number')
    })

    it('startup left a "linked" relation from the admin user to a permission', async () => {
        const res = await relationGetByEntityId(admin_user_id)
        expect(res.status).toBe(200)

        const link = res.data.data.find(r => r.entity_1 === 'user' && r.entity_2 === 'permission' && r.id_1 === admin_user_id)
        expect(link).toBeDefined()
        expect(link.relation_type).toBe('linked')
        expect(link.deleted_at).toBeNull()
    })

    it('GET /api/permission/id/:id resolves the administrator permission from that link', async () => {
        const res = await relationGetByEntityId(admin_user_id)
        const link = res.data.data.find(r => r.entity_1 === 'user' && r.entity_2 === 'permission' && r.id_1 === admin_user_id)

        const permission = await permissionGetById(link.id_2)
        expect(permission.status).toBe(200)
        expect(permission.data.data.name).toBe(ADMINISTRATOR_PERMISSION_NAME)
        expect(permission.data.data.deleted_at).toBeNull()
    })

    it('GET /api/relation/entity/permission lists the seeded link', async () => {
        const res = await relationGetByEntity('permission')
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.entity_1 === 'user' && r.id_1 === admin_user_id)).toBeDefined()
    })

    it('grants the admin user all four verbs', () => {
        expect(permission_service.can(admin_user_id, 'read')).toBe(true)
        expect(permission_service.can(admin_user_id, 'create')).toBe(true)
        expect(permission_service.can(admin_user_id, 'edit')).toBe(true)
        expect(permission_service.can(admin_user_id, 'delete')).toBe(true)
    })

    it('denies a verb that is not one of the four', () => {
        expect(permission_service.can(admin_user_id, 'download')).toBe(false)
        expect(permission_service.can(admin_user_id, '')).toBe(false)
        expect(permission_service.can(admin_user_id, undefined)).toBe(false)
    })

    // ----------------------------------------------------------------------------
    // A user with no link at all.
    // ----------------------------------------------------------------------------

    it('resolves no permission for a user nothing points at', () => {
        expect(permission_service.getByUserId(USER_ID)).toBeNull()
    })

    it('denies every verb to a user with no permission attached', () => {
        expectEverythingDenied(USER_ID)
    })

    it('ignores a relation from the same user that does not point at a permission', async () => {
        // The user is now on one side of a live relation, but it is a tag link. Rights come
        //  from a permission and nothing else, so this must still grant nothing.
        await tagPost({ name: TAG_NAME, metadata: '{}' })
        const tag = await tagGetByName(TAG_NAME)
        tag_id = tag.data.data.id

        const res = await relationPost({
            id_1: USER_ID,
            entity_1: 'user',
            id_2: tag_id,
            entity_2: 'tag',
            relation_type: 'linked',
            note: DISTRACTION_NOTE
        })
        expect(res.status).toBe(201)

        distraction_id = await findRelationIdByNote(DISTRACTION_NOTE)
        expect(typeof distraction_id).toBe('number')

        expect(permission_service.getByUserId(USER_ID)).toBeNull()
        expectEverythingDenied(USER_ID)
    })

    // ----------------------------------------------------------------------------
    // A link built by hand, and everything that can happen to it afterwards.
    // ----------------------------------------------------------------------------

    it('POST /api/permission/ creates the permission the user will be linked to', async () => {
        const res = await permissionPost({
            name: PERMISSION_NAME,
            can_read: true,
            can_create: false,
            can_edit: false,
            can_delete: false
        })
        expect(res.status).toBe(201)

        const created = await permissionGetByName(PERMISSION_NAME)
        permission_id = created.data.data.id
        expect(typeof permission_id).toBe('number')
    })

    it('relates the user to the permission with a "linked" relation', async () => {
        const res = await relationPost({
            id_1: USER_ID,
            entity_1: 'user',
            id_2: permission_id,
            entity_2: 'permission',
            relation_type: 'linked',
            note: NOTE
        })
        expect(res.status).toBe(201)

        relation_id = await findRelationIdByNote(NOTE)
        expect(typeof relation_id).toBe('number')
    })

    it('stores the user as id_1 and the permission as id_2', async () => {
        const res = await relationGetById(relation_id)
        expect(res.status).toBe(200)
        expect(res.data.data.entity_1).toBe('user')
        expect(res.data.data.id_1).toBe(USER_ID)
        expect(res.data.data.entity_2).toBe('permission')
        expect(res.data.data.id_2).toBe(permission_id)
        expect(res.data.data.relation_type).toBe('linked')
    })

    it('resolves the permission through the link', () => {
        const permission = permission_service.getByUserId(USER_ID)
        expect(permission).not.toBeNull()
        expect(permission.id).toBe(permission_id)
        expect(permission.name).toBe(PERMISSION_NAME)
    })

    it('grants exactly the verbs the linked permission carries', () => {
        expect(permission_service.can(USER_ID, 'read')).toBe(true)
        expect(permission_service.can(USER_ID, 'create')).toBe(false)
        expect(permission_service.can(USER_ID, 'edit')).toBe(false)
        expect(permission_service.can(USER_ID, 'delete')).toBe(false)
    })

    it('GET /api/relation/entity_id/:id finds the link from the user side', async () => {
        const res = await relationGetByEntityId(USER_ID)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    it('GET /api/relation/entity_id/:id finds the link from the permission side', async () => {
        const res = await relationGetByEntityId(permission_id)
        expect(res.status).toBe(200)
        expect(res.data.data.find(r => r.id === relation_id)).toBeDefined()
    })

    it('takes a flag change into account straight away, with no new link and no new session', async () => {
        // The flags are read from the database on every check, never carried in the session
        //  token: this is what makes a permission change effective without a re-login.
        const res = await updatePermission(permission_id, { can_create: true, can_edit: true })
        expect(res.status).toBe(200)

        expect(permission_service.can(USER_ID, 'read')).toBe(true)
        expect(permission_service.can(USER_ID, 'create')).toBe(true)
        expect(permission_service.can(USER_ID, 'edit')).toBe(true)
        expect(permission_service.can(USER_ID, 'delete')).toBe(false)

        const link = await relationGetById(relation_id)
        expect(link.data.data.id_2).toBe(permission_id)
    })

    it('PUT /api/permission/update/ renames the permission without breaking the link', async () => {
        const res = await updatePermission(permission_id, { name: RENAMED_PERMISSION })
        expect(res.status).toBe(200)

        const link = await relationGetById(relation_id)
        expect(link.data.data.id_2).toBe(permission_id)

        const permission = permission_service.getByUserId(USER_ID)
        expect(permission.name).toBe(RENAMED_PERMISSION)
        expect(permission_service.can(USER_ID, 'read')).toBe(true)
    })

    it('revokes every right when the link is soft-deleted', async () => {
        const res = await relationDelete(relation_id)
        expect(res.status).toBe(200)

        // The permission itself is untouched — it is the link that is gone.
        const permission = await permissionGetById(permission_id)
        expect(permission.data.data.deleted_at).toBeNull()

        expect(permission_service.getByUserId(USER_ID)).toBeNull()
        expectEverythingDenied(USER_ID)
    })

    it('gives the rights back when the link is restored', async () => {
        const res = await updateRelation(relation_id, { deleted_at: false })
        expect(res.status).toBe(200)

        expect(permission_service.can(USER_ID, 'read')).toBe(true)
        expect(permission_service.can(USER_ID, 'create')).toBe(true)
    })

    it('revokes every right when the permission is soft-deleted, link intact', async () => {
        const res = await permissionDelete(permission_id)
        expect(res.status).toBe(200)

        // The link is still live and still readable: it is the permission that is in the trash.
        const link = await relationGetById(relation_id)
        expect(link.data.data.deleted_at).toBeNull()
        expect(link.data.data.id_2).toBe(permission_id)

        expect(permission_service.getByUserId(USER_ID)).toBeNull()
        expectEverythingDenied(USER_ID)
    })

    it('gives the rights back when the permission is restored', async () => {
        const res = await updatePermission(permission_id, { deleted_at: false })
        expect(res.status).toBe(200)

        expect(permission_service.can(USER_ID, 'read')).toBe(true)
        expect(permission_service.can(USER_ID, 'create')).toBe(true)
        expect(permission_service.can(USER_ID, 'delete')).toBe(false)
    })

    it('changes the rights when the link is pointed at another permission', async () => {
        const created = await permissionPost({
            name: SECOND_PERMISSION_NAME,
            can_read: true,
            can_create: true,
            can_edit: true,
            can_delete: true
        })
        expect(created.status).toBe(201)

        const second = await permissionGetByName(SECOND_PERMISSION_NAME)
        second_permission_id = second.data.data.id

        const res = await updateRelation(relation_id, { id_2: second_permission_id })
        expect(res.status).toBe(200)

        expect(permission_service.getByUserId(USER_ID).id).toBe(second_permission_id)
        expect(permission_service.can(USER_ID, 'delete')).toBe(true)
    })

    it('is a role, not a per-user record: a second user linked to the same row gets the same rights', async () => {
        const res = await relationPost({
            id_1: SECOND_USER_ID,
            entity_1: 'user',
            id_2: second_permission_id,
            entity_2: 'permission',
            relation_type: 'linked',
            note: SECOND_NOTE
        })
        expect(res.status).toBe(201)

        second_relation_id = await findRelationIdByNote(SECOND_NOTE)
        expect(typeof second_relation_id).toBe('number')

        expect(permission_service.getByUserId(SECOND_USER_ID).id).toBe(second_permission_id)
        expect(permission_service.can(SECOND_USER_ID, 'delete')).toBe(true)

        // And revoking one user's link leaves the other one alone.
        await relationDelete(second_relation_id)
        expectEverythingDenied(SECOND_USER_ID)
        expect(permission_service.can(USER_ID, 'delete')).toBe(true)
    })

    afterAll(async () => {
        await relationDelete(relation_id)
        await relationDelete(distraction_id)
    })
})
