const Relation = require('./model')
const { getSystemTime } = require('../core/time')

const _ = {}

// Resolves the deleted_at value to store on update. The client sends a boolean, never a
//  timestamp: true stamps the current system time, false clears the mark, and null (or an
//  absent field) does nothing — it keeps whatever the stored row already had.
_.resolveDeletedAt = (current, deleted_at_flag) => {
    if (deleted_at_flag === undefined || deleted_at_flag === null) return current ? current.deleted_at : null
    return deleted_at_flag ? getSystemTime() : null
}

// Builds a Relation from a create request. The id is generated by the model and deleted_at
//  defaults to null; note is optional and stored as null when absent.
_.buildForCreate = (body) => {
    const relation = new Relation()
    relation.id_1 = body.id_1
    relation.entity_1 = body.entity_1
    relation.id_2 = body.id_2
    relation.entity_2 = body.entity_2
    relation.relation_type = body.relation_type
    relation.note = body.note ?? null
    return relation
}

// Builds a Relation from an update request. It resolves deleted_at itself from the stored
//  row and the client flag, so the controller does not deal with timestamps.
_.buildForUpdate = (current, body) => {
    const deleted_at = _.resolveDeletedAt(current, body.deleted_at)
    const relation = new Relation()
    relation.setClass(body.id, body.id_1, body.entity_1, body.id_2, body.entity_2, body.relation_type, body.note, deleted_at)
    return relation
}

module.exports = _
