const File = require('./model')
const { getSystemTime } = require('../core/time')

const _ = {}

// Resolves the deleted_at value to store on update. The client sends a boolean, never a
//  timestamp: true stamps the current system time, false clears the mark, and null (or an
//  absent field) does nothing — it keeps whatever the stored row already had.
_.resolveDeletedAt = (current, deleted_at_flag) => {
    if (deleted_at_flag === undefined || deleted_at_flag === null) return current ? current.deleted_at : null
    return deleted_at_flag ? getSystemTime() : null
}

// Builds a File from a create request. The id is generated by the model and deleted_at
//  defaults to null; the client provides only the data fields.
_.buildForCreate = (body) => {
    const file = new File()
    file.name = body.name
    file.hash_256_sha = body.hash_256_sha
    file.relative_path = body.relative_path
    file.extension = body.extension
    return file
}

// Builds a File from an update request. It resolves deleted_at itself from the stored row
//  and the client flag, so the controller does not deal with timestamps.
_.buildForUpdate = (current, body) => {
    const deleted_at = _.resolveDeletedAt(current, body.deleted_at)
    const file = new File()
    file.setClass(body.id, body.name, body.hash_256_sha, body.relative_path, body.extension, deleted_at)
    return file
}

module.exports = _
